import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://geisthub.vercel.app/font/sans.css" />
        <link rel="stylesheet" href="https://geisthub.vercel.app/font/mono.css" />
      </head>
      <body className="antialiased font-sans">
        {children}
      </body>
    </html>
  );
}