services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: agendamento
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backEnd
    env_file:
      - ./backEnd/.env.docker
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    # Se precisar mapear volumes para desenvolvimento, descomente:
    # volumes:
    #   - ./backEnd:/app

  frontend:
    build: ./frontEnd
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # Se precisar mapear volumes para desenvolvimento, descomente:
    # volumes:
    #   - ./frontEnd:/app

volumes:
  db_data: