version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: agendamento
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backEnd
    env_file:
      - ./backEnd/.env.docker
    volumes:
      - ./backEnd:/app
    ports:
      - "3333:3333"
    depends_on:
      - db

  frontend:
    build: ./frontEnd
    volumes:
      - ./frontEnd:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data: